### ISSUE TITLE
Validation Problem

### ISSUE THREAD

**Issue by fdahmadi** [TRUEPIC/queryql#41]
Hi
Thanks for your queryql

This is my defineValidation

`defineValidation(schema) {`
`  return {`
`    'filter:host[=]': schema.string().required(),`
`    'page:size': schema.number().max(100),`
`  }`
`}`

When there is no filter in my request it dose not check filters. It checks only if filter is exists in my request.
I have to check it myself

`if (!req.query.filter || !req.query.filter.host) {`
`  res.status(400).send();`
`  return;`
`}`

**Comment by jstayton** [comment]
Hey Farhad,

Yes, unfortunately, that's how it currently works: a filter is only validated if it's included in the query string.

I don't love how querier validation works due to this and a few other reasons – like not being able to validate one filter based on the value of another – but I haven't had a chance to rework it yet.

I'll make sure this is possible when that happens.

Thanks for the report!
