### ISSUE TITLE
'is not' operator always throw validation error

### ISSUE THREAD

**Issue by vligas** [TRUEPIC/queryql#9]
Hi,

I was trying to create a querier that accepts an 'is not' operator but it seems like there is a validation that prevents the values of the filters to be null however the KnexAdapter stablish that the `is not` operator needs to be null.

Minimal example: 
```js
// Querier
class TestQuerier extends QueryQL {
  defineSchema(schema) {
    schema.filter('test', '=')
    schema.filter('testing', '!=')
    schema.filter('testNull', 'is not')
    schema.sort('test')
    schema.sort('testing')
    schema.page()
  }
}

// Test
  test('returns `true` if valid', () => {
    const querier = new TestQuerier(
      {
        filter: { test: 123, testNull: { 'is not': null} },
        sort: 'test',
        page: 2,
      },
      knex('test')
    )

    expect(querier.validate()).toBe(true)
    // ValidationError: filter:testNull[is not] must be one of [array, boolean, number, string]
  })

// If i try to pass a string
  test('returns `true` if valid', () => {
    const querier = new TestQuerier(
      {
        filter: { test: 123, testNull: { 'is not': 'foo'} },
        sort: 'test',
        page: 2,
      },
      knex('test')
    )

    expect(querier.validate()).toBe(true)
    // ValidationError: filter:testNull[is not] must be [null]
  })
```

I think that it  have something to do with the method `defineValidation` in the `FilterParser`.

Thanks in advance

**Comment by jstayton** [comment]
Hey Victor,

Thanks for the issue! The example was really helpful.

You're spot on with where the issue is located in the code. I have a fix on the way.

This has me thinking though: values such as `null` and boolean are really difficult to encode in a query string. Packages like [qs](https://www.npmjs.com/package/qs) have a specific option you can enable to support `null`, but I don't think it's too common. And there's nothing for boolean.

I'll think about that some more, but any ideas on your end?

**Comment by vligas** [comment]
Hey, thanks for the fast response.

In fact it was a little hard to figure out how to make express to accept a null value for qs parameter, mmm I think that you could let the end user what a null value or boolean means in the actual query, something that let you transform the arguments before validation take place. Actually that can be accomlplish using the custom methods for the filters like the following:

```js
class TestQuerier extends QueryQL {
    defineSchema(schema) {
      schema.filter('test', '=')
      schema.filter('testing', '!=')
      schema.filter('testNull', 'is not')
      schema.sort('test')
      schema.sort('testing')
      schema.page()
    }
    
    'filter:testNull[is not]'(builder, {field, value, operator}) {
        if (value === 'null') {
            return builder.whereNotNull(field)
        }
        return builder
    }
}
``` 
but this let the end user the responsability to replace the functionality provided by the adapter. So in my case I would rather prefer and interface like this:

```js
const parseNull = value => value === 'null' ? null : undefined

class TestQuerier extends QueryQL {
    defineSchema(schema) {
      schema.filter('test', '=')
      schema.filter('testing', '!=')
      schema.filter('testNull', 'is not').transform(parseNull)
      schema.sort('test')
      schema.sort('testing')
      schema.page()
    }
}
``` 
this way you only have to worry about transform the data and no replace all the logic that the adapter have stablish to use for the operator. But this is just an idea.

Thanks again for the lib and the fast response!

**Comment by jstayton** [comment]
Hey Victor,

Yes, you can definitely accomplish this with a custom filter method like your example. But as you say, I don't want to place that burden on the developer. Even your `transform` idea – which could be interesting for some other purposes – feels like a burden when you just expect it to work.

Since there are only a few ways you can represent `null` in a query string, I'm thinking it makes sense to just handle those out-of-the-box. Same with boolean, since it's not easy to represent either.

I'll see if I can implement that sometime soon.

Thanks again!

**Comment by jstayton** [comment]
Just FYI: v0.7.0 now supports `'null'` as a string or an empty string to represent `null`, so you don't have to do any transform of your own.
